export const actionTypes={
    INIT:{
        FETCHED:'FETCHED',
        DENEME_STATE:'DENEME-STATE'
    },
    CLONE:{
        SETGROUPITEM:'SETGROUPITEM',
        ADD_CLONEITEM:'ADD-CLONEITEM',
        REMOVE_CLONEITEM:'REMOVE-CLONEITEM',
        CREATE_TABLE:'CREATE-TABLE',
        GET_CLONEITEMS:'GET-CLONEITEMS'
    },
    UI:{
        UI_GETINITCALC:"UI-GETINITCALC"
    }
}
